### ISSUE TITLE
Threshold Definition

### ISSUE THREAD

**Issue by ServetKocak** [finloop/usad-torchlightning#1]
Hi @finloop I am just wondering how did you define the threshold? I am looking at the paper but they didn't explain how did they set it up? Because you define it as "thresholds = np.arange(0.0, np.max(y_pred), np.max(y_pred)/50)", and in the loop when it searches for the best f1 score index, if it gives 0, then all the test dataset will be labelled as an anomaly.

**Comment by finloop** [comment]
Hi, thanks for opening the issue!
> Hi @finloop I am just wondering how did you define the threshold? 

The model outputs a continuous variable (anomaly score), a threshold is a value above which a window is considered to be an anomaly. As you said, the paper didn't explain how they choose said value, that's why I run a simple search.

> Because you define it as "thresholds = np.arange(0.0, np.max(y_pred), np.max(y_pred)/50)", and in the loop when it searches for the best f1 score index, if it gives 0, then all the test dataset will be labelled as an anomaly.

Yes, that might be an issue. I don't remember that I actually faced it when I run the model. Here's a better approach (the authors of the paper probably used something like this), but I never found time to replace it: [link](https://machinelearningmastery.com/roc-curves-and-precision-recall-curves-for-classification-in-python/). Feel free to fork this repository and fix it. Any contributions are welcome :+1:
